/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina - www.xs-labs.com
 * All rights reserved.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

typedef NSInteger CKCursorKind;

FOUNDATION_EXPORT CKCursorKind CKCursorKindUnexposedDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindStructDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUnionDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindClassDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindEnumDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFieldDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindEnumConstantDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFunctionDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindVarDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindParmDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCInterfaceDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCCategoryDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCProtocolDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCPropertyDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCIvarDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCInstanceMethodDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCClassMethodDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCImplementationDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCCategoryImplDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTypedefDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXMethod;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNamespace;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLinkageSpec;
FOUNDATION_EXPORT CKCursorKind CKCursorKindConstructor;
FOUNDATION_EXPORT CKCursorKind CKCursorKindDestructor;
FOUNDATION_EXPORT CKCursorKind CKCursorKindConversionFunction;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTemplateTypeParameter;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNonTypeTemplateParameter;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTemplateTemplateParameter;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFunctionTemplate;
FOUNDATION_EXPORT CKCursorKind CKCursorKindClassTemplate;
FOUNDATION_EXPORT CKCursorKind CKCursorKindClassTemplatePartialSpecialization;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNamespaceAlias;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUsingDirective;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUsingDeclaration;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTypeAliasDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCSynthesizeDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCDynamicDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXAccessSpecifier;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastDecl;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCSuperClassRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCProtocolRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCClassRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTypeRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXBaseSpecifier;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTemplateRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNamespaceRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindMemberRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLabelRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindOverloadedDeclRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindVariableRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastRef;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstInvalid;
FOUNDATION_EXPORT CKCursorKind CKCursorKindInvalidFile;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNoDeclFound;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNotImplemented;
FOUNDATION_EXPORT CKCursorKind CKCursorKindInvalidCode;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastInvalid;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUnexposedExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindDeclRefExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindMemberRefExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCallExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCMessageExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindBlockExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindIntegerLiteral;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFloatingLiteral;
FOUNDATION_EXPORT CKCursorKind CKCursorKindImaginaryLiteral;
FOUNDATION_EXPORT CKCursorKind CKCursorKindStringLiteral;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCharacterLiteral;
FOUNDATION_EXPORT CKCursorKind CKCursorKindParenExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUnaryOperator;
FOUNDATION_EXPORT CKCursorKind CKCursorKindArraySubscriptExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindBinaryOperator;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCompoundAssignOperator;
FOUNDATION_EXPORT CKCursorKind CKCursorKindConditionalOperator;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCStyleCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCompoundLiteralExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindInitListExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindAddrLabelExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindStmtExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindGenericSelectionExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindGNUNullExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXStaticCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXDynamicCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXReinterpretCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXConstCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXFunctionalCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXTypeidExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXBoolLiteralExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXNullPtrLiteralExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXThisExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXThrowExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXNewExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXDeleteExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUnaryExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCStringLiteral;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCEncodeExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCSelectorExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCProtocolExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCBridgedCastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindPackExpansionExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindSizeOfPackExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLambdaExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCBoolLiteralExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastExpr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUnexposedStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLabelStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCompoundStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCaseStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindDefaultStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindIfStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindSwitchStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindWhileStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindDoStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindForStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindGotoStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindIndirectGotoStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindContinueStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindBreakStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindReturnStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindAsmStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCAtTryStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCAtCatchStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCAtFinallyStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCAtThrowStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCAtSynchronizedStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCAutoreleasePoolStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindObjCForCollectionStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXCatchStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXTryStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXForRangeStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindSEHTryStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindSEHExceptStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindSEHFinallyStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindMSAsmStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindNullStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindDeclStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastStmt;
FOUNDATION_EXPORT CKCursorKind CKCursorKindTranslationUnit;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindUnexposedAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindIBActionAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindIBOutletAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindIBOutletCollectionAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXFinalAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindCXXOverrideAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindAnnotateAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindAsmLabelAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastAttr;
FOUNDATION_EXPORT CKCursorKind CKCursorKindPreprocessingDirective;
FOUNDATION_EXPORT CKCursorKind CKCursorKindMacroDefinition;
FOUNDATION_EXPORT CKCursorKind CKCursorKindMacroExpansion;
FOUNDATION_EXPORT CKCursorKind CKCursorKindMacroInstantiation;
FOUNDATION_EXPORT CKCursorKind CKCursorKindInclusionDirective;
FOUNDATION_EXPORT CKCursorKind CKCursorKindFirstPreprocessing;
FOUNDATION_EXPORT CKCursorKind CKCursorKindLastPreprocessing;

@class CKTranslationUnit;
@class CKSourceLocation;

@interface CKCursor : NSObject
{
@protected
    
    CKCursorKind       _kind;
    NSString         * _displayName;
    NSString         * _kindSpelling;
    CKCursor         * _definition;
    CKCursor         * _semanticParent;
    CKCursor         * _lexicalParent;
    CKCursor         * _canonical;
    CKCursor         * _referenced;
    CKSourceLocation * _location;
    BOOL               _isDefinition;
    BOOL               _isDeclaration;
    BOOL               _isReference;
    BOOL               _isPreprocessing;
    BOOL               _isExpression;
    BOOL               _isAttribute;
    BOOL               _isInvalid;
    BOOL               _isStatement;
    BOOL               _isTranslationUnit;
    BOOL               _isUnexposed;
    void             * _cxCursorPointer;
}

@property( atomic, readonly ) CKCursorKind        kind;
@property( atomic, readonly ) NSString          * displayName;
@property( atomic, readonly ) NSString          * kindSpelling;
@property( atomic, readonly ) CKCursor          * definition;
@property( atomic, readonly ) CKCursor          * semanticParent;
@property( atomic, readonly ) CKCursor          * lexicalParent;
@property( atomic, readonly ) CKCursor          * canonical;
@property( atomic, readonly ) CKCursor          * referenced;
@property( atomic, readonly ) CKSourceLocation  * location;
@property( atomic, readonly ) BOOL                isDefinition;
@property( atomic, readonly ) BOOL                isDeclaration;
@property( atomic, readonly ) BOOL                isReference;
@property( atomic, readonly ) BOOL                isPreprocessing;
@property( atomic, readonly ) BOOL                isExpression;
@property( atomic, readonly ) BOOL                isAttribute;
@property( atomic, readonly ) BOOL                isInvalid;
@property( atomic, readonly ) BOOL                isStatement;
@property( atomic, readonly ) BOOL                isTranslationUnit;
@property( atomic, readonly ) BOOL                isUnexposed;

+ ( id )cursorWithLocation: ( CKSourceLocation * )location translationUnit: ( CKTranslationUnit * )translationUnit;
- ( id )initWithLocation: ( CKSourceLocation * )location translationUnit: ( CKTranslationUnit * )translationUnit;

@end
