/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina <macmade@eosgarden.com>
 * All rights reserved.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/
 
/* $Id$ */

@class CKTranslationUnit;

typedef NSInteger CKDiagnosticSeverity;

FOUNDATION_EXPORT CKDiagnosticSeverity CKDiagnosticSeverityIgnored;
FOUNDATION_EXPORT CKDiagnosticSeverity CKDiagnosticSeverityNote;
FOUNDATION_EXPORT CKDiagnosticSeverity CKDiagnosticSeverityWarning;
FOUNDATION_EXPORT CKDiagnosticSeverity CKDiagnosticSeverityError;
FOUNDATION_EXPORT CKDiagnosticSeverity CKDiagnosticSeverityFatal;

@interface CKDiagnostic: NSObject
{
@protected
    
    CXDiagnostic         _cxDiagnostic;
    NSString           * _string;
    NSString           * _spelling;
    CKDiagnosticSeverity _severity;
    NSArray            * _fixIts;
    NSUInteger           _line;
    NSUInteger           _column;
    NSRange              _range;
    
@private
    
    RESERVED_IVARS( CKDiagnostic, 5 );
}

@property( atomic, readonly ) CXDiagnostic         cxDiagnostic;
@property( atomic, readonly ) NSString           * string;
@property( atomic, readonly ) NSString           * spelling;
@property( atomic, readonly ) CKDiagnosticSeverity severity;
@property( atomic, readonly ) NSArray            * fixIts;
@property( atomic, readonly ) NSUInteger           line;
@property( atomic, readonly ) NSUInteger           column;
@property( atomic, readonly ) NSRange              range;

+ ( NSArray * )diagnosticsForTranslationUnit: ( CKTranslationUnit * )translationUnit;
+ ( id )diagnosticWithTranslationUnit: ( CKTranslationUnit * )translationUnit index: ( NSUInteger )index;
- ( id )initWithTranslationUnit: ( CKTranslationUnit * )translationUnit index: ( NSUInteger )index;

@end
